-- Atlas.lua — UV coordinates of the Lucide icon TGA atlas
-- AUTO-GENERATED by scripts/export-icons.py
-- DO NOT edit manually — overwritten on each release
--
-- Layout 16px: 512×512px, grid 32×32, 16px cells
--   UV: left=col/32, right=(col+1)/32, top=row/32, bottom=(row+1)/32
--
-- Layout 24px: 512×512px, grid 21×21, 24px cells
--   UV: left=col/21, right=(col+1)/21, top=row/21, bottom=(row+1)/21

local Craft = LibStub("Craft-1.0")

Craft.Icons = Craft.Icons or {}

-- ─── Atlas 16px ────────────────────────────────────────────────────
Craft.Icons._atlas16 = {
    -- System (col 0-7) — required by Craft components
    ["check"] = { 0, 0 },
    ["minus"] = { 1, 0 },
    ["chevron-down"] = { 2, 0 },
    ["chevron-right"] = { 3, 0 },
    ["chevron-up"] = { 4, 0 },
    ["x"] = { 5, 0 },
    ["eye"] = { 6, 0 },
    ["eye-off"] = { 7, 0 },
    -- Convenience (col 8-23) — for devs using Craft
    ["info"] = { 8, 0 },
    ["circle-check"] = { 9, 0 },
    ["circle-alert"] = { 10, 0 },
    ["triangle-alert"] = { 11, 0 },
    ["loader-circle"] = { 12, 0 },
    ["search"] = { 13, 0 },
    ["plus"] = { 14, 0 },
    ["chevron-left"] = { 15, 0 },
    ["arrow-left"] = { 16, 0 },
    ["arrow-right"] = { 17, 0 },
    ["settings"] = { 18, 0 },
    ["user"] = { 19, 0 },
    ["menu"] = { 20, 0 },
    ["panel-left"] = { 21, 0 },
    ["grip-vertical"] = { 22, 0 },
    ["square-check"] = { 23, 0 },
}

-- ─── Atlas 24px ────────────────────────────────────────────────────
Craft.Icons._atlas24 = {
    ["check"] = { 0, 0 },
    ["minus"] = { 1, 0 },
    ["chevron-down"] = { 2, 0 },
    ["chevron-right"] = { 3, 0 },
    ["chevron-up"] = { 4, 0 },
    ["x"] = { 5, 0 },
    ["eye"] = { 6, 0 },
    ["eye-off"] = { 7, 0 },
    ["info"] = { 8, 0 },
    ["circle-check"] = { 9, 0 },
    ["circle-alert"] = { 10, 0 },
    ["triangle-alert"] = { 11, 0 },
    ["loader-circle"] = { 12, 0 },
    ["search"] = { 13, 0 },
    ["plus"] = { 14, 0 },
    ["chevron-left"] = { 15, 0 },
    ["arrow-left"] = { 16, 0 },
    ["arrow-right"] = { 17, 0 },
    ["settings"] = { 18, 0 },
    ["user"] = { 19, 0 },
    ["menu"] = { 20, 0 },
    ["panel-left"] = { 0, 1 },
    ["grip-vertical"] = { 1, 1 },
    ["square-check"] = { 2, 1 },
}
