-- Atlas.lua — grid coordinates of the Lucide icon TGA atlas
-- AUTO-GENERATED by scripts/export-icons.py
-- DO NOT edit manually — overwritten on each release
--
-- Layout: 512×512px, grid 8×8, 64px cells
--   (56px icon centered with a 4px transparent gutter — supersampled)
--   UV: left=col/8, right=(col+1)/8, top=row/8, bottom=(row+1)/8

local Craft = LibStub("Craft-1.0")
local _BUILD = ((select(2, ...)) or {}).CRAFT_BUILD or 0  -- this copy's build (see Craft.register)

-- Versioned (production bug #1): skip if a newer/equal Icons atlas is already loaded.
-- Atlas.lua and Icons.lua share the _buildOwner marker; Icons.lua attaches its methods
-- only when _buildOwner matches its own build.
if Craft.Icons and Craft.Icons._buildOwner and Craft.Icons._buildOwner >= _BUILD then return end
Craft.Icons = { _buildOwner = _BUILD }

Craft.Icons._div = 8  -- cells per row/column (for UV math in Icons.lua)

Craft.Icons._atlas = {
    -- System — required by Craft components
    ["check"] = { 0, 0 },
    ["minus"] = { 1, 0 },
    ["chevron-down"] = { 2, 0 },
    ["chevron-right"] = { 3, 0 },
    ["chevron-up"] = { 4, 0 },
    ["x"] = { 5, 0 },
    ["eye"] = { 6, 0 },
    ["eye-off"] = { 7, 0 },
    -- Convenience — for devs using Craft
    ["info"] = { 0, 1 },
    ["circle-check"] = { 1, 1 },
    ["circle-alert"] = { 2, 1 },
    ["triangle-alert"] = { 3, 1 },
    ["loader-circle"] = { 4, 1 },
    ["search"] = { 5, 1 },
    ["plus"] = { 6, 1 },
    ["chevron-left"] = { 7, 1 },
    ["arrow-left"] = { 0, 2 },
    ["arrow-right"] = { 1, 2 },
    ["settings"] = { 2, 2 },
    ["user"] = { 3, 2 },
    ["menu"] = { 4, 2 },
    ["panel-left"] = { 5, 2 },
    ["grip-vertical"] = { 6, 2 },
    ["square-check"] = { 7, 2 },
}
